PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX gdpo: <https://www.ramsprinciplesofgooddesign.com/>

SELECT DISTINCT ?principleClass ?targetExpression WHERE {
  ?principleClass rdfs:subClassOf gdpo:GDPO0000003 ;
                  rdfs:subClassOf ?restriction .
  FILTER(?principleClass != gdpo:GDPO0000003)
  ?restriction a owl:Restriction ;
               owl:onProperty gdpo:GDPO0000454 ;
               owl:allValuesFrom ?targetExpression .
}
ORDER BY ?principleClass
