PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gdpo: <https://www.ramsprinciplesofgooddesign.com/>

SELECT DISTINCT ?artifact ?artifactLabel WHERE {
  ?evaluation a gdpo:GDPO0000044 ;
              gdpo:GDPO0000045 ?artifact .
  OPTIONAL { ?artifact rdfs:label ?artifactLabel . }
}
ORDER BY ?artifact
